version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: securityDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CLI123
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
